CREATE TABLE users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT UNIQUE NOT NULL,
password_hash TEXT NOT NULL,
is_admin INTEGER NOT NULL DEFAULT 0,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE books (
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
slug TEXT UNIQUE NOT NULL,
description TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE chapters (
id INTEGER PRIMARY KEY AUTOINCREMENT,
book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
title TEXT NOT NULL,
ord INTEGER NOT NULL DEFAULT 0
);


CREATE TABLE documents (
id INTEGER PRIMARY KEY AUTOINCREMENT,
chapter_id INTEGER NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
title TEXT NOT NULL,
content TEXT NOT NULL,
is_published INTEGER NOT NULL DEFAULT 0,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME
);
